### ISSUE TITLE
1. As a guest I want to see a list of talent to view and familiarize myself with

### ISSUE THREAD

**Issue by KateySt** [Team-Maksym/.github#1]
1. Each profile should display general information:
• Avatar
• Name
• Position
_2. I want to be able to view more talents by clicking on the arrow at the bottom_

**TASK FOR:**
  1.Fronrend
  - [x] [1.1 Creating a list of users (talentList)](https://github.com/Team-Maksym/frontend/issues/6)
  - [x] [1.2 Creating a small card for a profile (smallTalentCard)](https://github.com/Team-Maksym/frontend/issues/23)
  - [x] [1.3 Implementation of pagination](https://github.com/Team-Maksym/frontend/issues/7)

 2.Backend
 - [x] [1.1 Creating the Talent and Position entities](https://github.com/Team-Maksym/backend/issues/6)
 - [x] [1.2 Configuring Database Interaction Methods](https://github.com/Team-Maksym/backend/issues/7)
 - [x] [1.3 Creating a controller that produces a list of DTO TalentProfile](https://github.com/Team-Maksym/backend/issues/8)
 - [x] [1.4 Creating a DTO TalentProfile with the given fields](https://github.com/Team-Maksym/backend/issues/9)
