### ISSUE TITLE
12. I am, as a Sponsor want to have possibility to register my own profile

### ISSUE THREAD

**Issue by tetyaZyna** [Team-Maksym/.github#12]
1. I want to see window where I can choose my role in StarLight (Talent or Sponsor) 
2. I want add general information about me in my profile
-   Name
-   Position (and company)
-   Avatar
3. My profile must be invisible for others Sponsors and Talents

**TASK FOR:**
  1.Fronrend

 2.Backend

- [ ] [12.1 Add role SPONSOR#118](https://github.com/Team-Maksym/backend/issues/118)
- [ ] [12.2 Create an endpoint POST /sponsors#119](https://github.com/Team-Maksym/backend/issues/119)
- [ ] [12.3 Sponsor login#120](https://github.com/Team-Maksym/backend/issues/120)
- [ ] [12.4 Sponsor edit#121](https://github.com/Team-Maksym/backend/issues/121)
