### ISSUE TITLE
14. I am, as a Sponsor, want to have possibility to add Kudos at Proofs

### ISSUE THREAD

**Issue by tetyaZyna** [Team-Maksym/.github#14]
1. I want to see a list with placed Kudos
2. I want to add few Kudos
3. I can’t add more Kudos, than I have on my profile at this moment
4. Talent can’t add Kudos on Proofs
5. I want to see the number of Kudos already marked on Proof by me

**TASK FOR:**
  1.Fronrend

 2.Backend

- [ ] [14.1 New method (list with placed kudos in /sponsors/{sponsor-id}/kudos)#111](https://github.com/Team-Maksym/backend/issues/111)
- [ ] [14.2 Add new kudos (POST /proofs/{proof-id}/kudos)#112](https://github.com/Team-Maksym/backend/issues/112)
- [ ] [14.3 New method (number of Kudos already marked in /sponsors/{sponsor-id}/kudos)#113](https://github.com/Team-Maksym/backend/issues/113)
