### ISSUE TITLE
2. As a talent I want to be able to view the personal profile of another talent for reference

### ISSUE THREAD

**Issue by KateySt** [Team-Maksym/.github#2]
1. I want to see a panel with detailed information about the talent
• Avatar
• Contact details
• Name
• Education
• Age
• Position
• Experience
2. I want to see a list of the talent's talents, with a short description of each talent
3. I want to see detailed information about the talent's talent after clicking on its description

**TASK FOR:**
  1.Frontend
  - [x] [2.1. Create components with registration forms and login](https://github.com/Team-Maksym/frontend/issues/9)
  - [x] [2.2. Implementation of the component in which we will see the talents themselves (wrapperTalent)](https://github.com/Team-Maksym/frontend/issues/10)
  - [x] [2.3. Implement a component with following information (bigTalentCard)](https://github.com/Team-Maksym/frontend/issues/13)
  - [x] [2.4. Implementation of the talent`s post component (talentPost)](https://github.com/Team-Maksym/frontend/issues/15)
  - [x] [2.5. Implementation of components containing certificates (talentProofs) and components of the certificate itself (talentProof)](https://github.com/Team-Maksym/frontend/issues/17)
  - [x] [2.6. Implementation of the recommendation component (Recommendation), which contains (smallTalentCard)](https://github.com/Team-Maksym/frontend/issues/18)

 2.Backend
 - [x] [2.1 Creating a controller that emits a TalentProfile DTO](https://github.com/Team-Maksym/backend/issues/5)
 - [x] [2.2 Creating a Role entity](https://github.com/Team-Maksym/backend/issues/3)
 - [x] [2.3 Creating a configuration for prescribing rights for each role](https://github.com/Team-Maksym/backend/issues/1)
 - [x] [2.4 Creating a controller to register](https://github.com/Team-Maksym/backend/issues/2)
 - [x] [2.5 Creating a talent registration process](https://github.com/Team-Maksym/backend/issues/10)
 - [x] [2.6 Creating an Authentication](https://github.com/Team-Maksym/backend/issues/11)
 - [x] [2.7 Creating and processing a token](https://github.com/Team-Maksym/backend/issues/17)
