### ISSUE TITLE
3. As a talent I want to be able to edit my own profile

### ISSUE THREAD

**Issue by KateySt** [Team-Maksym/.github#3]
1. On my own page, I want to see a pencil symbol next to the information I can edit
2. After clicking on the pencil symbol, I want to be able to edit a panel with basic information about myself. Ability to change:
• Avatar
• Contact details
• Name
• Education
• Age
• Position
• Experience
3. When editing a talent description, I want a field with detailed information to be opened immediately for editing
4. I want to be able to add and remove photos of certificates that confirm my personal talents

**TASK FOR:**
  1.Fronrend
  - [x] [3.1. Create component (modalEditProfile) with a modal window with a form editing the fields](https://github.com/Team-Maksym/frontend/issues/24)
  - [x] [3.2. Add a pencil to the component (bigTalentCard) for editing data when clicking on it](https://github.com/Team-Maksym/frontend/issues/25)
  - [x] [3.3. Change the skill using the button that will appear when hovering over the skill](https://github.com/Team-Maksym/frontend/issues/26)
  - [x] [3.4. Implement the addition of a new skill using a button that, after clicking on it, a modal window appears (modalFormSkill)](https://github.com/Team-Maksym/frontend/issues/27)
  - [x] [3.5. Implement the removal of the skill using the button that will appear when hovering over the skill](https://github.com/Team-Maksym/frontend/issues/28)

 2.Backend
 - [x] [3.1 Create DTO TalentSession](https://github.com/Team-Maksym/backend/issues/14)
 - [x] [3.2 Create a PATCH controller "/talents/{talent-id}"](https://github.com/Team-Maksym/backend/issues/15)
